research_analysis_task:
  description: >
    Find potential users in the {keyword} field who may be interested in the company's business.
    The company's business is to do marketing services for various brands in Greater China.
  expected_output: >
    the name of one target brand
  agent: global_business_research_analyst

client_contact_information_task:
  description: >
    Find the key contact person in charge of marketing, branding or e-commerce direction 
    of the brand and his/her email information through the target brand's official website, 
    LinkedIn and other channels, and then a colleague will try to establish contact with the 
    contact person and promote the company's marketing services. Don't stop until you find
    the contact information of the ten brands.
  expected_output: >
    “brand-contact-email” given brand
  agent: client_contact_information_specialist


business_development_outreach_specialist_task:
  description: >
    After receiving a potential client's brand name, contact person, and email address, your
    task is to research the brand's business model and marketing strategy, identify how our
    services align with their needs, and craft a personalized outreach email that speaks directly
    to their goals. You'll position our company as a strategic partner, using clear, tailored
    messaging to initiate meaningful conversations and drive engagement.
  expected_output: >
    a email to the contact person of the brand
  agent: business_development_outreach_specialist


brand_researcher_analyst_task:
  description: >
    Research the brand's online presence and business performance. Use tools to analyze website
    traffic and interest trends. Assess the brand's market visibility and sales potential, and 
    provide clear, actionable recommendations on whether the brand is worth pursuing for collaboration.
  expected_output: >
    a report on the brand's market visibility and growth potential
  agent: brand_researcher_analyst

customer_solutions_specialist_task:
  description: >
    Evaluate client-specific information—including business objectives, 
    budget, target audience, and desired outcomes—to determine the most 
    suitable service model. Based on this assessment, recommend either the 
    performance-based model or the flat-fee model, ensuring the proposed approach 
    aligns with the client’s goals and maximizes the effectiveness of our marketing services.
    
    Our company offers the following two service models:

    Performance-Based Model
    Under this model, we charge a commission based on the actual sales 
    generated through our marketing initiatives. This results-oriented approach 
    ensures that costs are directly tied to performance outcomes.
    Recommended for clients seeking scalable growth with minimal upfront investment, 
    particularly those open to long-term collaboration and revenue sharing.

    Flat-Fee Model
    In this model, clients pay a predetermined fixed fee for a one-time marketing 
    service. This approach provides cost certainty and clearly defined deliverables.
    Recommended for clients with specific campaign objectives, limited timelines, or 
    fixed budgets who prefer a straightforward and independent engagement.
  expected_output: >
    Customized ending solutions for users
  agent: customer_solutions_specialist